#!/usr/bin/env bash

## Go/Package/GoFile.list-to-symvars
## Read @list file(s), create a symvar for each var or const ($key) declaration.
## Keywords 'var' and 'const' are represented here by variable '$key'.

## @var: files must contain valid golang global variable declarations
## General syntax:
##      var NAME TYPE = VALUE   -- fully declared, with name, type, value
##      var NAME = VALUE        -- type is inferred from value
##      var NAME TYPE           -- var will be set to the type's 0-value by go
## NAME can also be a list:
##      var N1, N2, N3 TYPE = VALUE
##      var N1, N2, N3 = VALUE
##      var N1, N2, N3 TYPE
## Declarations can be also be in a var (...) block, and will be
## missing the 'var' keyword on each line.

parse_values() {
    local -i num=$1
    local value="$2"
    local -i p=0
    local -i v=0
    local c
    (( num == 1 )) && values[0]="$value" && return
    while (( p < ${#value} )); do
        c=${value:$p:1}
        p+=1
        [[ $c == ',' && -z $INQUOTE ]] && v+=1 && continue
        values[$v]+=$c
        [[ $c != '"' ]] && continue
        if [[ -n $INQUOTE ]]; then INQUOTE= ; else INQUOTE=1; fi
    done
}

parse_declaration() {
    ## Expecting declarations of the form:
    ##      var name type
    ##      var name1, name2, name3 type
    ##      var name type = value
    ##      var name = value
    ##      var name1, name2, name3 type = v1, v2, v3
    ##      var name1, name2, name3 = v1, v2, v3
    local declaration="$1" && shift
    local -a dw=( $declaration )
    local -i i j
    local name type value
    ## empty names[] array is declared in caller
    local -a values
    local -A sv

    i=0
    ## var must be the first word in the declaration.
    [[ ${dw[i++]} == $key ]] || return

    ## Declaration may have one name or several names separated by commas.
    while (( i < ${#dw[@]} )); do 
        name=${dw[i++]}
        [[ $name == *, ]] && names+=(${name%,}) && continue
        names+=($name)
        break
    done

    ## Next must be the variable type or '=' and value.
    type=${dw[i++]}
    [[ $type == '=' || ${dw[$i]} == '=' ]] && {
        ## Go will infer the variable type from the value if no type is given.
        parse_values ${#names[@]} "${declaration#*=}"
        [[ ${#values[@]} == ${#names[@]} ]] || {
            warn "number of values must match number of names"
            return
        }
    }
    [[ $type == '=' ]] && type=

    ## Now we have names, type, and/or values, so should be all set.
    for ((j=0; j<${#names[@]}; j++)); do 
        name="${names[j]}"
        value="${values[j]}"
        if [[ -n $value ]]; then
            ## We have the name and value, may have the type or not.
            if [[ -n $type ]]; then
                sv[name]=$key:$type:$name
                sv[value]="$key $name $type =$value"
            else
                sv[name]=$key:$name
                sv[value]="$key $name =$value"
            fi
        else
            ## We have only the name, no value, so must have the type.
            sv[name]=$key:$type:$name
            sv[value]="$key $name $type"
        fi
        ## Replace names[j] entry with associated symvar name for caller's use:
        names[$j]="${sv[name]}"

        ## Now we have the symvar name and value, ready to save.

        ## Create symvar if it does not exist, or rewrite value if -f is given:
        [[ ! -h ${sv[name]} || -n $FORCE ]] &&
            symvar -f "${sv[name]}" "${sv[value]}" &&
                continue

        warn "symvar file exists: ${sv[name]} =${sv[value]}"

    done
    return
}

readListFile() {
    local listfile="$1"
    local SAVE="$2"
    local line
    local BLANK='^ *$'
    local BLOCKSTART='^\s*$key *\('
    local BLOCKEND='^\s*\)'
    local OPENCURLYBRACKET='^ *$key .*{$'
    local inblock=
    local -a names
    local name

    while IFS= read -r line; do 
        ## skip comments, blank lines, start and end of var(...) block:
        [[ $line == //* ]] && continue
        [[ $line =~ $BLANK ]] && continue
        [[ $line =~ $BLOCKSTART ]] && inblock=1 && continue
        [[ $line =~ $BLOCKEND ]] && inblock= && continue
        [[ $line =~ $OPENCURLYBRACKET ]] && {
            warn "${0#*lib/} $listfile: unable to handle '$key ... {' declarations"
            return 1
        }
        names=()
        if [[ -n $inblock ]]; then
            parse_declaration "$key $line"
        else 
            parse_declaration "$line"
        fi

        [[ -n $SAVE ]] || continue
        for name in "${names[@]}"; do
            printf "%s %s\n" "$name" "$listfile" >> %VARS
        done
    done < "$listfile"
}

main() {
    local FORCE
    [[ $1 == -f ]] && FORCE=1 && shift
    local -a files=("$@")
    local file

    (( $# > 0 )) && {
        ## Process each argument @$key: file.
        ## Don't write to %VARS map.
        for file in "${files[@]}"; do
            readListFile "$file" ""
        done
        return
    }

    ## Called with no arguments, process each @var: or @const: file in @ORDER.

    ## delete map file which contains varnames and associated @file name:
    [[ -e %VARS ]] && rm %VARS

    ## @ORDER list file defines the element files for the target program
    while IFS= read -r file; do
        ## parse list file type from name, e.g., @var:x, @const:y, ...
        key=${{file#@}%:*}
        key=${file#@}
        key=${key%:*}
        warn "readListFile $key $file" && continue
        [[ $file == @$key:* ]] || continue
        [[ $key == 'var' || $key == 'const' ]] || continue
        readListFile "$key" "${file%% *}" "save to map"
    done < @ORDER
}

main "$@"

